version: 0.0
os: linux
files:
  - source: fileku/
    destination: /var/www/html/
    overwrite: true
file_exists_behavior: OVERWRITE
branch_config:
    wip\/.*: ~ 
    main:
        deploymentGroupName: latihanCodedeployGroup
        deploymentGroupConfig:
            serviceRoleArn: arn:aws:iam::350251222225:role/latihanRoleGroup